apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atomicwatch-hostlogs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atomicwatch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: atomicwatch-hostlogs
