---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atomicwatch-basicauth
  namespace: atomicwatch
spec:
  encryptedData:
    users: AgBuWChPpgDWVbULsVq7MZQemBdqpMhB7lXVgj8S3GgiV94Orp7Vb1RpdqRk01irUO4+RY2zlqVCBkUPzdZll83tQbyVDnG+3IcbuOBbbDIfiJVh+81vEOLcXVQbceOHykI84ovlUmiWolgSvWkX7yGLm78NrxlGsfTx7QiX4K1Pi7nGTd4YJ1fyvwGrkHlqsbu0JcRB9udHt0Hxrsl1ERXk11gLC3bgQ2jKwPYoHOVqU9V7adXxL7RufISRLHRUkA2FbH6meILs2Nyzq2aIyrVAjX+OH415DheJUzYtlbdr0Ay8FvBooGcl9ePlM+3RPRjN5EZE8fV+BQ50iFCRzbtl4IFZSdTdw6+B4x+hYn6FuhxIlGbsQO11tgtK1P+vJFEFkFpICh3oqN/89Y+0Q5Yahm0SpuD4Vf5ISLbLp5AigFzGTNOC1t6ML5jzOQ/CJ4d4qZ9z1ClFETCIzaGSx2BjOWu32hR2NHYUayzFTe/Un++ufU6l/2YhMEQz2BgE5mnypMfTjHeCAkdBkeyl3uI0ak24XcBOdbi+KUT6d470zKhODu+uYcF2H6WHHEBZUNqhL30RBJDZrQ3S4ka6f5fLEkK9vdhuKr80ULJ+isly/KFYc/3y3XwEzMUyI2pDt+RNGa131kl1NmiCqcWbhwAFV4EXlFpsB6XlI0+IQqtaHdW7fR+7VrCmA/7GNZXUvPWfiXlqZjSKV1huy/0Lqd7CXfvwLmN666bfeTO588BSvGIBGzcRAh7HmX0hGPwn0iDwM4PL+hXgX3ALw20=
  template:
    metadata:
      name: atomicwatch-basicauth
      namespace: atomicwatch
