---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atomicwatch-basicauth
  namespace: atomicwatch
spec:
  encryptedData:
    users: AgAONXxPAlf+UL8kz9RG8TIuVdQQileC3oVmKdX4JCDkbXQVn4ALK7GsZvRa6GWnbARsNLvl2d/nIzAbAHQcsVF0HUu4/0j8XW6wnbXqm3sY09atRSyPIesplutHVNitrCv23aHNG64OfAw6keChW0Xyk944HwYnWlG6hmm6UeiH1nw5YCAlVn6UVy8bI7FHuUDVAxQ4IXtan74KUNuuk/laLzVdj6Krs8H3IAo8xJkOzVeuIxtVOHGfXeLHqQ8xyTMXDn4HIgBE74YM7LDMiS66/RihuWgQn9JkHBRyqo3MQkY9TP5J0pGqEds582r/fVw1Sfdl0BbAemqxhVpH8wku03IlEjERWENwx09MOGVgNJk75Mh7m6vfXhdqVKm0elKWiHgn6Hvh4bNN/2fipv37wCTBwZTkzV/wAiQkzT3AIezZOktRNsGOGMAa15GQyEYQJ0+Vx+Gz5Pq2W1YMzTU7SnHwsYsiazzXQm0weC31L3wSFQAr5xyGj24eNgo96do+Imoan/P/4FK/G7FrLqwLHVR3kirAOrED+NLaYoi0Z1LVa6ZHAY2VVHqmLSzROD6T/yYDnJJBtFQyGskw1SvCdfRVtLayuh8rNjaPGMR+LlvcJaPS3JKyT97zNnAbjhQHmanv1TvaFRInjb0L4zDukYXGB3JqkitqMa2EQOIHVBvr1QpluSmxyyqbNWzZSHJBBhpzA2sIOGkBMvoam/vbYTXg3EFtQgWRC0kI3KMDxrPw4u/ZyJkNkiVW
  template:
    metadata:
      name: atomicwatch-basicauth
      namespace: atomicwatch
