---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atomicwatch-basicauth
  namespace: atomicwatch
spec:
  encryptedData:
    users: AgAFzw8CC0xXd3AE7Uv/n01JvIhcfz0QM61h1lFTdVdrGTSUwLfKJcCvhNw4x/f/vQzVFU3cq7ozxwwR+X1qLYn/01KJ/i1dYK29Fpf9Y9d2fRAwuCn7ur6ion22iE/yANxt2so0dBZ58VeCaqFxkChnnOlZ6SQ8odHdS9jIhd5oG03RYXI18WD954icTK7wchHwlteTf6O6VA0yROUoWsM6+UCDP90cmtbOWjTmbIjrpjT/FdciPT3ESKWyJrvFMXn9lKg/nfcjUL6LARXhfaItnF+gOH4XtKeXAir1zZqpJHzOKvRGcqxDmM49FACWlg10wBW0o3du+2MeS+B4X73Wpi+e5HHX0tAnrJfs8CzaFKLqns3kiLjPglc1MWr6jHSE5oJDcY7ekkS/bkK9qIiV9iK/zYKBxXXrr3atJlI8BqSOMA88qO/puqLod942HcJ1QNORZzzWMLlgiT7h0gVJ72pMV8EEHz0SxgPX33cwTjLvpTXgGecRRBIm9b8laCKMLTQhZcZiByHHXM0gg10bXcwXg2CLwZmTeX407TkUMjuiAYL4bvUmu2JkDQGHJcSPfg42Dcd52pmQF7Jfs/rMUmjO8yMGteXiq30dgj0atA+9jd2r+7lDuzle7oHAMUzCHpI9rr0bv77YZhDo5YH/70QO3DMEVWuH9BjknnjsIj5Y158Ux7EZZewlzv6nItZBLbQ2JLpEYTq3Qd4boAT6QV9hpB8wKJR70swtNyB9sB/uauz1q3zsZMfq
  template:
    metadata:
      name: atomicwatch-basicauth
      namespace: atomicwatch
