apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atomicwatch
  namespace: argocd
  annotations:
    team/owner: ops
spec:
  project: default
  source:
    repoURL: https://github.com/maxeodev/atomicwatch
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: atomicwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 60s
