---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: atomicwatch-basicauth
  namespace: atomicwatch
spec:
  encryptedData:
    users: AgA2dfvHCHNkEGKmNm4qThpSSrevY0UPM6Hy3aajOyU+I9P1mn4ciVGJaXif8DHfIj/V7m75EYyDU2mdW6zx+7dZtjMXkGItvrJjQ6s/80U63M++oG91N4hSGBzk/1DhgfpeRwn8LsKazwud7MCqbyP1kf22eFZ/NCS2CKDs/OY6zScgYnI7BVSXypQ3FORO7ZRPFK1HFD2msRPXoIBOtZghzKEDTvtKwPrMascd2uhyvVpLJhq8hKJyVB2fEFu9pfdOAjfXJFHw0N+fPttA0rBeQTJbhyP/EC4NDee+awMor42vIGbMNPf0hZYsNTfUXDbNxUuEWwhhjEzCpLamJL4QjlT+A70X7zYxFAEbmnQ0ev/rP0quXwFuCEhBU1G6H779uJIBPWTHC1jJ5vgqoV8IjgdMS4ZSrFR9AXb3r0oJLPerVALQG7I2830oJrDd9Bt1OO3XwkSWl7lS2sqDOCNiCsmeGfS6Z6kZ9HeXtbXRIS/1inWzeGluaNBGNTPHFFgWqFaMdhO5aAZraHtTnlHBYR1AUgP27g1ftuYobqBx3q8GecyG0dswhnu2/E/GqK3AabY24UadYLQy9Z7742uV4qXV9/MbN2Fjk3cPxUIRWiqpIJgE2blXnTbOAPbJ9TTKvFyPH9exgUNHrPcAUHNBKqEt5fopWfzhoFUJIRgtHevVnnWcEynecivS/pNiKmUY5q84OVHWM6UkUqI0JVSRh/WSHecwdn9IsY0yEaNmHxRdE2X3gD/sXI2FbOHT2/LrOoumLw4kK95x3VM=
  template:
    metadata:
      name: atomicwatch-basicauth
      namespace: atomicwatch
